### ISSUE TITLE
Reading a csv file within a template

### ISSUE THREAD

**Issue by sandeepkunkunuru** [wallix/awless-templates#1]
This is a feature request/suggestion. In my opinion as awless provides a programming level abstraction to cloud automation what's needed (may be already supported) is a way to specify data for the program (csv would suffice)

If an awless template can read a csv file, tt would allow creating objects of same class at one place programmatically ex: 
- create ec2 instances from a list
- create subnets, subnetgroups from a list
- create route53 records from a list

Here are few examples (that were done using bash wrappers)
- User creation - https://gist.github.com/sandeepkunkunuru/1023d9f4a2594e33b5c6cd06a0a6a011
- Load balanced web app - https://gist.github.com/sandeepkunkunuru/91a93ac6c4bc6ba7a62af6d3981fc8ed

**Comment by simcap** [comment]
Thanks @sandeepkunkunuru , and sorry for the delay in the response. 

You are right in saying that `awless` needs to have  way to specify/inject data when running template. But we are more thinking of configuration and env data.

Going forward, we want to avoid mixing bash and awless: we have tried it it is cumbersome and fiddly. Our roadmap and soon upcoming features of `awless` will cater for those scenarios.

* when running a template: flag to specify extra `awless` template file that contains external data. `awless run mytemplate.aws --data production-env.aws` 
* `for` loop in the template language
* programmatic way (i.e. Go lib) to run a template, so you get all the flexibility of creating your own programs (and power of Go stlib)  to run templates.
* ...

In the meantime if you want to create cloud resources from CSV files it should be done through UNIX command piping ending up creating `awless` template file (i.e. translating CSV header+values to `awless` param=value) that can be then run safely. [csvkit](https://github.com/wireservice/csvkit) mught help with that.

**Comment by sandeepkunkunuru** [comment]
Thanks for the response, future features look fantastic esp. Go lib. Looking forward to seeing them.

Thanks for csvkit suggestion it looks great.
