### ISSUE TITLE
String interpolation for attribute values?

### ISSUE THREAD

**Issue by mattsears** [wallix/awless-templates#2]
Hi! Is it possible to add string interpolation for attribute values? For example:

```
subnet = create subnet cidr={subnet.cidr} vpc=$vpc name="#{$appName} Public Subnet A"
```
 
In a few of my templates, I'm wanting to identify the resource with the application name and/or environment value.

Thanks!

**Comment by fxaguessy** [comment]
Hello,

Yes, this is possible, but the syntax is a bit different :

```
subnet = create subnet cidr={subnet.cidr} vpc=$vpc name="#" + {appName} + " Public Subnet A" 
```
As you may have notice '+' is here the operator of string concatenation.

**Comment by mattsears** [comment]
@fxaguessy I was hoping for interpolation and not concatenation, but that's better than nothing.
